// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docsSidebar: [
    
    {
      type: 'doc',
      id: 'intro',
      label: 'Introduction',
    },
    {
      type: 'doc',
      id: 'get-started',
      label: 'Get Started',
    },

    // ---- Manual section (auto contents inside /manual) ----
    {
      type: 'category',
      label: 'Manual',
      link: { type: 'doc', id: 'manual/manual-home' },
      items: [
        { type: 'autogenerated', dirName: 'manual' },
      ],
    },

    // ---- Scripting Reference section (auto contents inside /scripting-reference) ----
    {
      type: 'category',
      label: 'Scripting Reference',
      link: { type: 'doc', id: 'scripting-reference/scripting-home' },
      items: [
        { type: 'autogenerated', dirName: 'scripting-reference' },
      ],
    },

    // ---- AUTO-GENERATE EVERY OTHER FOLDER IN DOCS ----
    {
      type: 'autogenerated',
      dirName: '.',   
    },
  ],
};

module.exports = sidebars;
